a04_WuQiting/p4/pizzeria/pizzas/urls.py
"""Defines URL patterns for pizzas."""
from django.urls import path
from . import views

app_name = 'pizzas'

urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # Page for Pizzas
    path('pizzas/', views.pizzas, name='pizzas'),
    # Toppings for the chosen pizza
    path('pizzas/<int:pizza_id>/', views.pizza, name='pizza'),
]

a04_WuQiting/p4/pizzeria/pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizzas.urls')),
]

a04_WuQiting/p4/pizzeria/pizzas/models.py
from tabnanny import verbose
from django.db import models

# Create your models here.

# 2. Define a model Pizza with a field called name, which will hold name values, such as Hawaiian
#  and Meat Lovers.
# 3. Define a model called Topping with fields called pizza and name. The pizza field should be a
#  foreign key to Pizza, and name should be able to hold values such as pineapple, Canadian
#  bacon, and sausage.
# 4. Register both models with the admin site (Test your work by using the admin site to enter
#  some pizza names and toppings and by using the Django shell to explore the data you
#  entered.)
# 5. Set the username and password for the superuser account to: admin, admin

class Pizza(models.Model):
    name = models.CharField(max_length = 200)

    def __str__(self):
        return self.name

class Topping(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    name = models.CharField(max_length = 200)

    class Meta:
        verbose_name_plural = "toppings"

    def __str__(self):
        return self.name

a04_WuQiting/p4/pizzeria/pizzas/views.py
from django.shortcuts import render

from .models import Pizza

# Create your views here.
def index(request):
    """Home page for pizzas"""
    return render(request, 'pizzas/index.html')

def pizzas(request):
    """show all pizzas"""
    pizzas = Pizza.objects.all()
    context = {'pizzas': pizzas}
    return render(request, 'pizzas/pizzas.html', context)

def pizza(request, pizza_id):
    """Show a single pizza and all its toppings"""
    pizza = Pizza.objects.get(id=pizza_id)
    toppings = pizza.topping_set.all()
    context = {'pizza': pizza, 'toppings': toppings}
    return render(request, 'pizzas/pizza.html', context)

a04_WuQiting/p4/pizzeria/pizzas/templates/pizzas/base.html
<p>
    <a href="{% url 'pizzas:index' %}">Learning Log</a> - 
    <a href="{% url 'pizzas:pizzas' %}">Pizzas</a>
</p>
{% block content %}{% endblock content %}

a04_WuQiting/p4/pizzeria/pizzas/templates/pizzas/index.html
{% extends "pizzas/base.html" %}

{% block content %}

<p>Create your favorite pizza with the best toppings!</p>

{% endblock content %}

a04_WuQiting/p4/pizzeria/pizzas/templates/pizzas/pizza.html
{% extends 'pizzas/base.html' %}

{% block content %}

    <p>Pizza: {{pizza}}</p>

    <p>Toppings:</p>
    <ul>
        {% for topping in toppings %}
            <li>
                <p>{{topping.name}}</p>
            </li>
        {% empty %}
            <li>There is currently no topping for this pizza.</li>
        {% endfor %}
    </ul>

{% endblock content %}

a04_WuQiting/p4/pizzeria/pizzas/templates/pizzas/pizzas.html
{% extends "pizzas/base.html" %}

{% block content %}

    <p>Pizzas</p>

    <ul>
        {% for pizza in pizzas %}
            <li>
                <a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza }}</a>
            </li>
        {% empty %}
            <li>No pizzas have been added yet.</li>
        {% endfor %}
    </ul>

{% endblock content %}